### ISSUE TITLE
Question about the api.js in routes folder

### ISSUE THREAD

**Issue by jacepp** [btford/angular-socket-io-seed#10]
I was curious as to how you would go about adding this to pass data from the api.js into sockets?

**Comment by btford** [comment]
1. `require('api');` in `route/socket.js`.
2. add listeners in `route/socket.js`

**Comment by jacepp** [comment]
Thank you for your response. I had figured it out eventually but forgot to close this issue, sorry about that. On a related topic, I ran into an instance where I needed <code>io.sockets.emit()</code> within <code>route/socket.js</code>. To do this I ended up doing the following:

<ol>
<li>Edited <code>var io = require('socket.io').listen(server);</code> to <code>module.exports.io = io = require('socket.io').listen(app);</code> in <code>app.js</code>.</li>
<li>Then added <code>var io = require('../app.js').io;</code> to <code>routes/socket.js</code></li>
</ol>

It worked like a charm. Thank you for creating these seeds, they were/are/will be a really big help to me and many others I am sure.
