### ISSUE TITLE
$scope.messages needs declaration

### ISSUE THREAD

**Issue by kentcdodds** [btford/angular-socket-io-seed#12]
I was getting a problem sending messages and it's because $scope.messages was never defined, so when we tried to push a message to it we were getting an error. Doing this solved the problem:

controllers.js:

``` javascript
function AppCtrl($scope, socket) {

  $scope.messages = [];

  // Socket listeners
  // ================

  socket.on('init', function (data) {

...
```

I figured it was such a small change that it would be easier to submit an issue than a pull request.

**Comment by btford** [comment]
Wrong repo. This should go here: https://github.com/btford/angular-socket-io-im
