### ISSUE TITLE
In "btford.socket-io" module why use $rootScope.$apply() in emit() while using $timeout in on()

### ISSUE THREAD

**Issue by d6u** [btford/angular-socket-io-seed#13]
In `btford.socket-io` module why use `$rootScope.$apply()` in `emit()` while using `$timeout` in `on()`

I know this maybe a bad place for asking this question, but what is the difference?

**Comment by btford** [comment]
It's to ensure `$apply` is called outside of the digest cycle.

**Comment by d6u** [comment]
@btford could `$timeout` do the same for `emit()`?

**Comment by btford** [comment]
`emit` is already always async.
