### ISSUE TITLE
ReferenceError: io is not defined

### ISSUE THREAD

**Issue by aCodeAlchemist** [btford/angular-socket-io-seed#19]
I am a newbie to angular, express and node. Please guide me if I am missing anything.

**Comment by infrarosso78** [comment]
+1

**Comment by enkodellc** [comment]
Try including this script to your page: https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js

**Comment by quy-ng** [comment]
@enkodellc it works but is there any reasons?

**Comment by enkodellc** [comment]
Read the documentation on socket.io it is required.

**Comment by ghost** [comment]
@enkodellc Thanks. it worked for me
